[workspace]
members = [
    "crates/audio-utils",
    "crates/audio-cleaning",
    "crates/pitch-detection",
    "crates/sound-synth",
    "crates/learning-tools",
    "crates/gui",
    "crates/playground",
]
resolver = "2"
