[package]
name = "pitch_perfecter"
version = "0.1.0"
edition = "2024"

[dependencies]
hound = "3.5.1"
rustfft = "6.1"
plotters = "0.3.7"
# sound_synth = { path = "../sound_synth" }
rand = "0.9.2"
pitch-detection = "0.3.0"
fundsp = "0.20.0"
